### PR TITLE
Warehouse notification

### LINKED ISSUE #1059: Add notification about no warehouses available
It's not immediately obvious to the user why factory products aren't being moved or are unavailable without warehouses or enough warehouse space. When a factory finishes producing a product, if one of these conditions is true a notification should be pushed to let the user know that they need a warehouse.

### PR DESCRIPTION
**Pull request by Inglonias**
Factories will now notify you when they go idle because warehouses are full. (Fixes #1059)

Because I am very bad at this game, I am unable to test this fix. Can someone else test this for me?

I also have created a method that tells you what percentage of a given warehouse is available for storage, only to realize there's really nowhere to put it. If this should be commented out or deleted for being unused, please let me know.

### CODE REVIEW

**Comment by ldicker83** [comment]
Going to merge this because it looks good, but does the method you added to ProductPool get used anywhere?

**Comment by DanRStevens** [comment]
Looks like there was some build failures when merging. Be aware that PRs from forked repos don't run the automated builds, so we don't get that checking before merging, unless we import the branch into the main repo first.

> OPHD/ProductPool.cpp:135:57: error: expected ';' before '}' token
  135 |  return (100 - (mCurrentStorageCount * 100 / mCapacity))
      |                                                         ^
      |                                                         ;
  136 | }

> OPHD/States/MapViewStateEvent.cpp: In member function 'void MapViewState::onFactoryProductionComplete(Factory&)':
OPHD/States/MapViewStateEvent.cpp:75:59: error: cannot convert 'Factory' to 'Structure*'
   75 |     Tile& factoryPos = structureManager.tileFromStructure(factory);
      |                                                           ^~~~~~~
      |                                                           |
      |                                                           Factory
     
> OPHD/States/MapViewStateEvent.cpp:80:49: error: cannot convert '<brace-enclosed initializer list>' to 'NotificationArea::Notification'
   80 |     NotificationArea::NotificationType::Warning});
      |                                                 ^
      
https://app.circleci.com/pipelines/github/OutpostUniverse/OPHD/2094/workflows/06c3e6d6-5e43-4cae-b432-217315503719/jobs/9543

**Comment by Inglonias** [comment]
Figures the change I can't test properly doesn't work. I'll fix it this week.

**Comment by ldicker83** [comment]
Happens to the best of us. You should have seen how badly I borked the build for OP2Utility 😱

**Comment by DanRStevens** [comment]
I've certainly done it a few times, even with the automated build system, and for errors affecting my own system.

Of course, if you're interested in making regular contributions, we could always add you to the repo so you can push branches directly, rather than through a fork. That would mean the automated builds would run for your branch, so you could get build feedback for all platforms.

**Comment by Inglonias** [comment]
> I've certainly done it a few times, even with the automated build system, and for errors affecting my own system.
> 
> Of course, if you're interested in making regular contributions, we could always add you to the repo so you can push branches directly, rather than through a fork. That would mean the automated builds would run for your branch, so you could get build feedback for all platforms.

I'm going to have to pass on joining the org. Knowing me, these contributions will be pretty irregular at best, and stop after a week or two at worst. 

That said, #1224 is awaiting review. It fixes the build issues, and I even tested the functionality of the change to make sure it works this time, thanks to the cheat code I discovered in the code!

**Pull request merged**
