### PR TITLE
Fix an out of bounds issue in the StructureInspector window that...

### PR DESCRIPTION
**Pull request by ldicker83**
... attempts to access a row in StringTable that isn't allocated.

Not sure how this one was missed? Realized it when it came to structures that employ Scientists.

### CODE REVIEW

**Comment by Brett208** [comment]
Sorry, that was probably my fault. Thanks for fixing.

**Comment by ldicker83** [comment]
No worries, I figured it was an oversight. I do that sort of thing all the time -_-

**Comment by DanRStevens** [comment]
I wonder if there is a way to auto size the `StringTable`, based on array data. Might be complicated by the 2D nature of the data though.

**Comment by Brett208** [comment]
Yeah, since I implemented it in a 1D vector under the hood it might be a bit complex to auto size. I think it would be a nice feature to add though if someone had the time on their hands.

**Pull request merged**
