### PR TITLE
Use Rectangle::to<NewBaseType>()

### PR DESCRIPTION
**Pull request by DanRStevens**
Use new `Rectangle::to<NewBaseType>()` method to simplify code.

Related:
PR https://github.com/lairworks/nas2d-core/pull/450 (introduced `Rectangle::to<NewBaseType()`)
Issue #206 Replace `isPointInRect` with `rect.contains(point)`

### CODE REVIEW

**Comment by DanRStevens** [comment]
Hmm, seems MSVC is complaining.

**Comment by cugone** [comment]
Collision with `Windows.h` header.

```
2>E:\Git\OPHD\src\Common.cpp(243,18): error C2872: 'Rectangle': ambiguous symbol
2>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\wingdi.h(4515,24): message : could be 'BOOL Rectangle(HDC,int,int,int,int)' (compiling source file ..\..\src\Common.cpp)
2>E:\Git\OPHD\nas2d-core\include\NAS2D\Renderer\Rectangle.h(22,1): message : or       'NAS2D::Rectangle' (compiling source file ..\..\src\Common.cpp)
2>E:\Git\OPHD\src\Common.cpp(243,9): error C3321: an initializer list is unexpected in this context
2>E:\Git\OPHD\src\Common.cpp(243,53): error C2062: type 'int' unexpected
2>E:\Git\OPHD\src\Common.cpp(243,71): error C2143: syntax error: missing ';' before '{'
2>E:\Git\OPHD\src\Common.cpp(243,76): error C2143: syntax error: missing ';' before '}'
2>E:\Git\OPHD\src\Common.cpp(243,77): error C2059: syntax error: ')'
```

**Comment by cugone** [comment]
Qualifying it with a namespace fixes the issue.

**Comment by cugone** [comment]
```
bool pointInRect_f(int x, int y, float rectX, float rectY, float rectW, float rectH)
{
	return NAS2D::Rectangle{rectX, rectY, rectW, rectH}.to<int>().contains(Point{x, y});
}
```

**Comment by DanRStevens** [comment]
Yeah, I figure adding a `NAS2D::` prefix will fix that. We should probably be adding those prefixes anyway, and getting rid of `using namespace` statements.

I'm got 3 different test runs going to verify some different possible solutions. I'll update once they finish.

**Comment by cugone** [comment]
Even better. The windows header isn't needed in `Common.cpp`. Take it out.

**Comment by DanRStevens** [comment]
Not sure about that. I see code such as:
```cpp
#if defined(WINDOWS) || defined(WIN32)
	MessageBoxA(WIN32_getWindowHandle(), msg.c_str(), title.c_str(), MB_OK | MB_ICONERROR | MB_TASKMODAL);
#else
	SDL_ShowSimpleMessageBox(SDL_MESSAGEBOX_ERROR, title.c_str(), msg.c_str(), NULL);
#endif
```

We probably need to clean that up first before removing the Windows header. That would be a separate PR.

**Comment by cugone** [comment]
Huh. I missed that. It must be a transitive include then.

**Pull request merged**
