### PR TITLE
Remove PVS-Studio comments

### PR DESCRIPTION
**Pull request by malryt**

### CODE REVIEW

**Comment by DanRStevens** [comment]
Ahh, hello and welcome.

I see you made an attempt at #644.

**Comment by malryt** [comment]
Yes, sorry this is my first time working on a project and I was having some trouble haha

**Comment by DanRStevens** [comment]
No worries. I specifically marked that one as "easy" for people to come by and try their hand at. Got to start somewhere.

**Comment by ldicker83** [comment]
Heya!

Good start? Unsure why you closed it versus continuing on to take care of the rest of the messages.

Anyway, hoping to see more contributions from you going forward!

**Pull request closed without merging**
